### PR TITLE
DO NOT MERGE Fix for NumSrcs feature creator to use with a KS

### PR DESCRIPTION
**Pull request by kashefy**
1. The mismatch in in ITD and ILD dimensions does not allow you to construct a 2d histogram. This is solved by checking which has fewer channels and usampling them to match that of the larger feature.
2. Small indexing fix when the duet feature is not a cell array.

DO NOT MERGE, NOT PROPERLY TESTED YET. I tried running test/trainNumSrcs.m but couldn't get past the DNNLocationKS got an error that I'm requesting AFE blocks that are in the future...

### CODE REVIEW

**Comment by ivo--t** [comment]
@kashefy , which branch of wp3 did you use? This error (what I believe it is) was fixed by me on the 20th of Sept in master.

**Comment by ivo--t** [comment]
@pmeier82 , please check these fixes.

**Comment by kashefy** [comment]
@ivo--t , not getting the error anymore, might have gone away when I pulled again from blackboard master.
No longer getting the error that I'm requesting blocks that are in the future.

@pmeier82, please review the changes in this pull request and let us know if this is what you were going for. If you can also test this on your end, that would be great.

**Comment by pmeier82-zz** [comment]
ad 1) no idea why the afe features are not in a cell array. MATLAB foo .. workaround is reasonable.
ad 2) yes. the assumption is that ILD and ITD have the same time-frequency resolution. I agree with upsampling the smaller side.

**Comment by kashefy** [comment]
Great thanks for checking

**Comment by kashefy** [comment]
Trained a dummy model using the mini flist and plugged it into the KS. It works.
Also no NaN's in the model's output but probability values for each number of sources bin and a valid decision. Only thing left is to train a good model.
Ready for merging.

**Pull request merged**
